In [1]:
import pandas as pd

In [2]:
rna_seq_subset = pd.read_csv('Data/supplementary_data_1.csv')
rna_seq_selection = pd.read_excel('Data/secretome_samples_for_RNAseq_170111.xlsx', sheet_name='all')
tegel_all = pd.read_csv('Data/Tegel.proteins.dt.csv')

In [3]:
rna_seq_subset

,sample_ID,genes,transgene.tpm,transgene.count,all.count.sample,Total.purified.protein_stock1.stock2_microg,amount_microgram
0,P6975_101,GNAS,5597.038909,31980.0,12273152.0,691.0,NaN
1,P6975_102,FCER2,21732.203720,251015.0,16740679.0,217.0,NaN
2,P6975_103,PGLYRP4,12636.520010,170690.0,13688781.0,708.0,NaN
3,P6975_104,CCL14,77993.613670,96414.0,13608601.0,206.0,NaN
4,P6975_105,NXPH2,57652.829300,441575.0,13271324.0,503.0,NaN
...,...,...,...,...,...,...,...
91,P6975_192,FLT3LG,274.981349,1779.0,15812792.0,0.0,no amount
92,P6975_193,CXCL13,32424.791620,70277.0,12878349.0,0.0,no amount
93,P6975_194,ADM5,7400.224726,27807.0,10771131.0,0.0,no amount
94,P6975_195,CCL20,38913.255080,52742.0,11882495.0,0.0,no amount
95,P6975_196,WT,NaN,NaN,NaN,NaN,NaN

In [4]:
rna_seq_selection

,Cultivation,Gene name,ENSG ID,Uniprot ID,ENSP ID,Process type,Construct theor seq (nt),Construct exp seq (nt),GC content exp [%],Construct seq (aa),...,Total purified protein (stock1 + stock2) [&micro;g],Total purified protein (stock1 + stock2) [nmol],Purification state,Purification batch,Purification started,Purification column,Purification comment,Purification finished,GROUP,Unnamed: 37
0,CU000973,OIT3,ENSG00000138315,Q8WWZ8,ENSP00000333900,full length without sp,GTGGCCCTAGATCCTTGTTCTGCTTACATCAGCCTGAATGAGCCCT...,GTGGCCCTAGATCCTTGTTCTGCTTACATCAGCCTGAATGAGCCCT...,55.1,VALDPCSAYISLNEPWRNTDHQLDESQGPPLCDNHVNGEWYHFTGM...,...,141,2.332661,Finished purification,1233.0,2016-07-21 13:41:41,PC000537,">80% purity, multiple gel bands",2016-07-27 15:39:22,1,highest cell count
1,CU001826,ACVR2A,ENSG00000121989,P27037,ENSP00000241416,ecd,ATACTTGGTAGATCAGAAACTCAGGAGTGTCTTTTCTTTAATGCTA...,ATCCTGGGCAGATCCGAGACACAGGAATGCCTGTTCTTCAACGCCA...,56.3,ILGRSETQECLFFNANWEKDRTNQTGVEPCYGDKDKRRHCFATWKN...,...,230,14.378595,Finished purification,1234.0,2016-07-21 13:41:54,PC000522,>80% purity,2016-07-27 16:35:13,1,highest cell count
2,CU001529,NCAM1,ENSG00000149294,P13591,ENSP00000480774,ecd,CTGCAGGTGGACATCGTGCCCAGCCAGGGCGAGATCAGCGTGGGCG...,CTGCAGGTCGACATCGTGCCCAGCCAGGGCGAGATCTCCGTGGGCG...,59.3,LQVDIVPSQGEISVGESKFFLCQVAGDAKDKDISWFSPNGEKLTPN...,...,1141,15.518531,Finished purification,1256.0,2016-07-28 15:08:04,PC000483,">80% purity, multiple gel bands",2016-08-03 13:31:04,1,highest cell count
3,CU001550,SRPX,ENSG00000101955,P78539,ENSP00000367794,full length without sp,TTCCCAGGATCGGGAGACTCACCACTAGAAGACGATGAAGTCGGGT...,TTTCCTGGCTCTGGCGACAGCCCTCTGGAAGATGACGAAGTGGGCT...,60.4,FPGSGDSPLEDDEVGYSHPRYKDTPWCSPIKVKYGDVYCRAPQGGY...,...,220,4.351868,Finished purification,1385.0,2016-09-01 12:48:20,PC000611,">80% purity, smear",2016-09-07 13:34:31,1,highest cell count
4,CU001554,WFDC12,ENSG00000168703,Q8WWY7,ENSP00000361871,full length without sp,GTTAAAGAGGGTATAGAGAAAGCAGGGGTTTGCCCAGCTGACAACG...,GTCAAAGAGGGCATCGAGAAGGCCGGCGTGTGCCCTGCCGATAACG...,59.9,VKEGIEKAGVCPADNVRCFKSDPPQCHTDQDCLGERKCCYLHCGFK...,...,281,23.546171,Finished purification,1363.0,2016-08-25 13:53:26,PC000568,>80% purity,2016-08-31 13:55:20,1,highest cell count
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,CU001413,FLT3LG,ENSG00000090554,P49771,ENSP00000468977,ecd,ACCCAGGACTGCAGCTTCCAGCACAGCCCCATCAGCAGCGACTTCG...,ACCCAGGACTGCTCCTTCCAGCACTCCCCTATCTCCAGCGACTTCG...,60.1,TQDCSFQHSPISSDFAVKIRELSDYLLQDYPVTVASNLQDEELCGG...,...,0,0.000000,NaN,NaN,NaT,NaN,NaN,NaT,7,no amount
92,CU001562,CCL28,ENSG00000151882,Q9NRJ3,ENSP00000354416,full length without sp,ATACTTCCCATTGCCTCCAGCTGTTGCACGGAGGTTTCACATCATA...,ATCCTGCCTATCGCCAGCTCCTGCTGCACCGAGGTGTCCCACCACA...,59.5,ILPIASSCCTEVSHHISRRLLERVNMCRIQRADGDCDLAAVILHVK...,...,0,0.000000,NaN,NaN,NaT,NaN,NaN,NaT,7,no amount
93,CU001567,CXCL13,ENSG00000156234,O43927,ENSP00000286758,full length without sp,GTTCTGGAGGTCTATTACACAAGCTTGAGGTGTAGATGTGTCCAAG...,GTGCTGGAAGTGTACTACACCTCCCTGCGGTGCAGATGCGTGCAGG...,57.6,VLEVYYTSLRCRCVQESSVFIPRRFIDRIQILPRGNGCPRKEIIVW...,...,0,0.000000,NaN,NaN,NaT,NaN,NaN,NaT,7,no amount
94,CU001656,ADM5,ENSG00000224420,C9JUS6,ENSP00000393631,full length without sp,CTGGACACTGCAGCCAGGCGAGGCCAGCACCAGGTCCCCCAGCACC...,CTGGATACCGCCGCTAGAAGAGGCCAGCACCAGGTGCCACAGCACA...,62.8,LDTAARRGQHQVPQHRGHVCYLGVCRTHRLAEIIYWIRCLHQGALG...,...,0,0.000000,NaN,NaN,NaT,NaN,NaN,NaT,7,no amount
95,CU001658,CCL20,ENSG00000115009,P78556,ENSP00000386273,full length without sp,GCAAGCAACTTTGACTGCTGTCTTGGATACACAGACCGTATTCTTC...,GCTTCCAACTTCGACTGCTGCCTGGGCTACACCGACCGGATCCTGC...,55.9,ASNFDCCLGYTDRILHPKFIVGFTRQLANEGCDINAIIFHTKKKLS...,...,0,0.000000,NaN,NaN,NaT,NaN,NaN,NaT,7,no amount

## Gene IDs comparison

In [30]:
gene_ids_1 = rna_seq_subset['genes'].to_list()
gene_ids_2 = rna_seq_selection['Gene name'].to_list()
gene_ids_3 = tegel_all['human_symbol'].to_list()

# Convert the lists to sets for easier comparison
set_gene_ids_1 = set(gene_ids_1)
set_gene_ids_2 = set(gene_ids_2)
set_gene_ids_3 = set(gene_ids_3)

# Find common elements (intersection) across all three sets
common_genes_all = set_gene_ids_1 & set_gene_ids_2 & set_gene_ids_3

# Pairwise intersections
common_genes_1_2 = set_gene_ids_1 & set_gene_ids_2
common_genes_1_3 = set_gene_ids_1 & set_gene_ids_3
common_genes_2_3 = set_gene_ids_2 & set_gene_ids_3

# Unique elements in each set
unique_to_list_1 = set_gene_ids_1 - set_gene_ids_3
unique_to_list_2 = set_gene_ids_2 - set_gene_ids_3

# Summary of the counts
print(f"Number of genes in gene_ids_1: {len(set_gene_ids_1)}")
print(f"Number of genes in gene_ids_2: {len(set_gene_ids_2)}")
print(f"Number of genes in gene_ids_3: {len(set_gene_ids_3)}")
print('')
print(f"Number of common genes across all three lists: {len(common_genes_all)}")
print(f"Number of common genes between gene_ids_1 and gene_ids_2: {len(common_genes_1_2)}")
print(f"Number of common genes between gene_ids_1 and gene_ids_3: {len(common_genes_1_3)}")
print(f"Number of common genes between gene_ids_2 and gene_ids_3: {len(common_genes_2_3)}")
print('')
print(f"Number of genes unique to gene_ids_1: {len(unique_to_list_1)}")
print(f"Number of genes unique to gene_ids_2: {len(unique_to_list_2)}")

# Optionally display some sample genes for validation
print('')
print("Genes unique to gene_ids_1 compared to Tegel's dataset:", list(unique_to_list_1))
print("Genes unique to gene_ids_2 compared to Tegel's dataset:", list(unique_to_list_2))

Number of genes in gene_ids_1: 96
Number of genes in gene_ids_2: 95
Number of genes in gene_ids_3: 2153

Number of common genes across all three lists: 75
Number of common genes between gene_ids_1 and gene_ids_2: 92
Number of common genes between gene_ids_1 and gene_ids_3: 76
Number of common genes between gene_ids_2 and gene_ids_3: 76

Number of genes unique to gene_ids_1: 20
Number of genes unique to gene_ids_2: 19

Genes unique to gene_ids_1 compared to Tegel's dataset: ['LACTB', 'HMGB1', 'CTSL', 'SHH', 'FURIN_2', 'HSP90B1', 'NCF1', 'H6PD', 'AGA', 'AGPS', 'MAN2B1', 'MMP14', 'GLCE', 'MYL1', 'GXYLT1', 'SVEP1', 'WT', 'FURIN_1', 'ASGR1', 'GNAS']
Genes unique to gene_ids_2 compared to Tegel's dataset: ['LACTB', 'HMGB1', 'CTSL', 'SHH', 'HSP90B1', 'NCF1', 'H6PD', 'AGA', 'CHST1', 'AGPS', 'MAN2B1', 'MMP14', 'GLCE', 'FURIN', 'MYL1', 'GXYLT1', 'SVEP1', 'ASGR1', 'GNAS']

## ENSEMBL IDs Comparison

In [37]:
ens_ids_1 = rna_seq_selection['ENSG ID'].to_list()
ens_ids_2 = tegel_all['ENSG.id'].to_list()

# Convert the lists to sets for easier comparison
set_ens_ids_1 = set(ens_ids_1)
set_ens_ids_2 = set(ens_ids_2)

# Find common elements (intersection) across all three sets
common_ensids_all = set_ens_ids_1 & set_ens_ids_2

# Unique elements in each set
unique_to_list_1 = set_ens_ids_1 - set_ens_ids_2
unique_to_list_2 = set_ens_ids_2 - set_ens_ids_1

# Summary of the counts
print(f"Number of Ensemble IDs in ens_ids_1: {len(set_ens_ids_1)}")
print(f"Number of Ensemble IDs in ens_ids_2: {len(set_ens_ids_2)}")
print('')
print(f"Number of common genes between the two lists: {len(common_ensids_all)}")
print('')
print(f"Number of Ensemble IDs to ens_ids_1: {len(unique_to_list_1)}")
print(f"Number of Ensemble IDs to ens_ids_2: {len(unique_to_list_2)}")

# Optionally display some sample genes for validation
print('')
print("Genes unique to ens_ids_1 compared to Tegel's dataset:", list(unique_to_list_1))

Number of Ensemble IDs in ens_ids_1: 95
Number of Ensemble IDs in ens_ids_2: 2153

Number of common genes between the two lists: 76

Number of Ensemble IDs to ens_ids_1: 19
Number of Ensemble IDs to ens_ids_2: 2077

Genes unique to ens_ids_1 compared to Tegel's dataset: ['ENSG00000103642', 'ENSG00000135047', 'ENSG00000168530', 'ENSG00000164690', 'ENSG00000049239', 'ENSG00000104774', 'ENSG00000038002', 'ENSG00000138604', 'ENSG00000165124', 'ENSG00000175264', 'ENSG00000158517', 'ENSG00000140564', 'ENSG00000157227', 'ENSG00000166598', 'ENSG00000151233', 'ENSG00000189403', 'ENSG00000087460', 'ENSG00000018510', 'ENSG00000141505']